
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ROG
 */
import java.sql.*;
import java.util.LinkedList;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Jadwal extends javax.swing.JFrame {

    /**
     * Creates new form Jadwal
     */
    isiHospital base;
    private Connection conn;
    private Statement stmt = null;
    private ResultSet rset = null;
    Queue antri = new LinkedList<String>();
    private String nama;
    private int counter = 0;

    public Jadwal(java.awt.Frame parent, boolean modal, isiHospital base) {
        initComponents();
        this.base = base;
        btnAntri.setEnabled(false);
        btnSelanjutnya.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boxJadwal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txNamaDokter = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnJadwal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfQueue = new javax.swing.JTextArea();
        btnSelanjutnya = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfAntrian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfAntrianSaya = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfKuota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfKonfirmasi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txJadwal = new javax.swing.JTextField();
        btnAntri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Jadwal Dokter");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon doctor.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.cyan));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Jadwal");

        boxJadwal.setBackground(new java.awt.Color(153, 153, 153));
        boxJadwal.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        boxJadwal.setForeground(new java.awt.Color(0, 0, 0));
        boxJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        boxJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxJadwalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Silahkan pilih jadwal:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addComponent(boxJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, 190));

        txNamaDokter.setEditable(false);
        txNamaDokter.setBackground(new java.awt.Color(204, 204, 204));
        txNamaDokter.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        txNamaDokter.setForeground(new java.awt.Color(0, 51, 51));
        txNamaDokter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txNamaDokter.setText("Nama Dokter");
        txNamaDokter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(255, 255, 255), java.awt.Color.white, java.awt.Color.cyan));
        txNamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaDokterActionPerformed(evt);
            }
        });
        jPanel1.add(txNamaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 90));

        btnKembali.setBackground(new java.awt.Color(153, 153, 153));
        btnKembali.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 0, 0));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon antrian/icon kembali.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 160, 50));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("atau");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        btnJadwal.setBackground(new java.awt.Color(153, 153, 153));
        btnJadwal.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon antrian/icon liat jadwal.png"))); // NOI18N
        btnJadwal.setText("Lihat Jadwal");
        btnJadwal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });
        jPanel1.add(btnJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 410, 390));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfQueue.setEditable(false);
        tfQueue.setColumns(20);
        tfQueue.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        tfQueue.setRows(5);
        jScrollPane1.setViewportView(tfQueue);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 210, 260));

        btnSelanjutnya.setBackground(new java.awt.Color(153, 153, 153));
        btnSelanjutnya.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnSelanjutnya.setForeground(new java.awt.Color(0, 0, 0));
        btnSelanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon antrian/icon ambil.png"))); // NOI18N
        btnSelanjutnya.setText("Selanjutnya");
        btnSelanjutnya.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSelanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelanjutnyaActionPerformed(evt);
            }
        });
        jPanel4.add(btnSelanjutnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 210, 50));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Antrian Sekarang");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        tfAntrian.setEditable(false);
        tfAntrian.setBackground(new java.awt.Color(0, 0, 0));
        tfAntrian.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        tfAntrian.setForeground(new java.awt.Color(255, 255, 255));
        tfAntrian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAntrian.setText("-");
        tfAntrian.setInheritsPopupMenu(true);
        jPanel4.add(tfAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 110, 80));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Daftar Antrian");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 30));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nomor Antrian Anda");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        tfAntrianSaya.setEditable(false);
        tfAntrianSaya.setBackground(new java.awt.Color(0, 0, 0));
        tfAntrianSaya.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        tfAntrianSaya.setForeground(new java.awt.Color(255, 255, 255));
        tfAntrianSaya.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAntrianSaya.setInheritsPopupMenu(true);
        tfAntrianSaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAntrianSayaActionPerformed(evt);
            }
        });
        jPanel4.add(tfAntrianSaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, -10, 740, 470));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon antrian/icon jadwal.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.cyan));

        tfKuota.setEditable(false);
        tfKuota.setBackground(new java.awt.Color(153, 153, 153));
        tfKuota.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        tfKuota.setForeground(new java.awt.Color(0, 0, 0));
        tfKuota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKuota.setText("Kuota");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon antrian/icon quota.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kuota : ");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Konfirmasi Email : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 360, 190));

        txJadwal.setBackground(new java.awt.Color(204, 204, 204));
        txJadwal.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        txJadwal.setForeground(new java.awt.Color(0, 51, 51));
        txJadwal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txJadwal.setText("JADWAL");
        txJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJadwalActionPerformed(evt);
            }
        });
        jPanel5.add(txJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 90));

        btnAntri.setBackground(new java.awt.Color(153, 153, 153));
        btnAntri.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnAntri.setForeground(new java.awt.Color(0, 0, 0));
        btnAntri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon antrian/icon ambil.png"))); // NOI18N
        btnAntri.setText("Ambil Antrian");
        btnAntri.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAntri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntriActionPerformed(evt);
            }
        });
        jPanel5.add(btnAntri, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 380, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAntriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntriActionPerformed
        String email = tfKonfirmasi.getText();
        String queryNama = "SELECT nama FROM BIODATA WHERE email LIKE '" + email + "'";
        try {
            conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Jadwal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rset = stmt.executeQuery(queryNama);
        } catch (SQLException ex) {
            Logger.getLogger(Jadwal.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while (rset.next()) {
                nama = rset.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Jadwal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //String nama = txNamaDokter.getText();
        String box = boxJadwal.getSelectedItem().toString();
        // ListDokter ls=new ListDokter (this,true,base)
        //   isiHospital base=new isiHospital();
        ListDokter dk = new ListDokter(this, true);

        for (Dokter d : base.hospitalList) {
            if (d.getNama().equalsIgnoreCase("Dr Denata")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Denata'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));

                            if (antri.size() != 10) {
                                int i = antri.size();
                                antri.add(nama);
                                String jmlh = String.valueOf(i);
                                tfKuota.setText(antri.size() + "/10");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                                return;
                            }

                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 10) {
                                int i = antri.size();
                                antri.add(nama);
                                String jmlh = String.valueOf(i);
                                tfKuota.setText(antri.size() + "/10");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                                return;
                            }
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 10) {
                                int i = antri.size();
                                antri.add(nama);
                                String jmlh = String.valueOf(i);
                                tfKuota.setText(antri.size() + "/10");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                                return;
                            }
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 10) {
                                int i = antri.size();
                                antri.add(nama);
                                String jmlh = String.valueOf(i);
                                tfKuota.setText(antri.size() + "/10");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                                return;
                            }
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 10) {
                                int i = antri.size();
                                antri.add(nama);
                                String jmlh = String.valueOf(i);
                                tfKuota.setText(antri.size() + "/10");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                                return;
                            }
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Maaf, dokter sedang libur");
                            return;

                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Maaf dokter sedang libur");
                            return;
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            } else if (d.getNama().equalsIgnoreCase("Dr Arsel")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Arsel'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 7) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/7");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 7) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/7");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 7) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/7");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 7) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/7");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 7) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/7");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon dokter sedang libur");
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon dokter sedang libur");
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            } else if (d.getNama().equalsIgnoreCase("Dr Frans")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Frans'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 5) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/5");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 5) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/5");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 5) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/5");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 5) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/5");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 5) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/5");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon maaf dokter sedang libur");
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon maaf dokter sedang libur");
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            } else if (d.getNama().equalsIgnoreCase("Dr Bryan")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Bryan'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 12) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/12");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }

                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 12) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/12");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 12) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/12");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 12) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/12");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 12) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/12");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon maaf dokter sedang libur");
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon maaf dokter sedang libur");
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            } else //(d.getNama().equalsIgnoreCase("Dr Axel")) {
            {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Axel'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 15) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/15");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }

                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 15) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/15");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 15) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/15");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 15) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/15");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            if (antri.size() != 15) {
                                int i = antri.size();
                                antri.add(nama);
                                tfKuota.setText(antri.size() + "/15");
                                antri.forEach((Object element) -> {
                                    tfQueue.append("" + element + "\n");
                                });
                                btnJadwal.setEnabled(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Mohon maaf kuota sudah penuh");
                            }
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon maaf dokter sedang libur");
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            JOptionPane.showMessageDialog(null, "Mohon maaf dokter sedang libur");
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            btnAntri.setEnabled(false);
            btnSelanjutnya.setEnabled(true);

        }
        String t = String.valueOf(antri.size());
        tfAntrianSaya.setText(t);


    }//GEN-LAST:event_btnAntriActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:\
     //   String nama = txNamaDokter.getText();
        String box = boxJadwal.getSelectedItem().toString();
        // ListDokter ls=new ListDokter (this,true,base)
        //   isiHospital base=new isiHospital();
   //     ListDokter dk = new ListDokter(this, true);

        for (Dokter d : base.hospitalList) {
            if (d.getNama().equalsIgnoreCase("Dr Denata")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Denata'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Budi");
                            antri.add("Tono");
                            antri.add("Alex");
                            antri.add("Rian");
                            antri.add("Raffi");
                            antri.add("Andre");
                            antri.add("Yuni");
                            antri.add("Vini");
                            String ant = antri.size() + "/10";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.add("Budi");
                            antri.add("Tono");
                            antri.add("Alex");
                            antri.add("Rian");
                            antri.add("Raffi");
                            antri.add("Andre");
                            antri.add("Yuni");
                            antri.add("Vini");

                            String ant = antri.size() + "/10";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Budi");
                            antri.add("Tono");
                            antri.add("Alex");
                            antri.add("Rian");

                            String ant = antri.size() + "/10";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Andre");
                            antri.add("Yuni");

                            String ant = antri.size() + "/10";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Rian");
                            antri.add("Raffi");
                            antri.add("Andre");
                            antri.add("Yuni");
                            antri.add("Vini");
                            String ant = antri.size() + "/10";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            antri.clear();
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            String ant = antri.size() + "/0";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            antri.clear();
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            String ant = antri.size() + "/0";
                            tfKuota.setText(ant);
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            } else if (d.getNama().equalsIgnoreCase("Dr Arsel")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Arsel'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Tono");
                            antri.add("Alex");
                            antri.add("Rian");
                            antri.add("Raffi");
                            antri.add("Andre");
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Alex");
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Rian");
                            antri.add("Raffi");
                            antri.add("Andre");
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Tono");
                            antri.add("Alex");
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Tono");
                            antri.add("Alex");
                            antri.add("Rian");
                            antri.add("Raffi");
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            String ant = antri.size() + "/7";
                            tfKuota.setText(ant);
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            } else if (d.getNama().equalsIgnoreCase("Dr Frans")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Frans'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Tono");
                            antri.add("Alex");
                            antri.add("Rian");

                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Tono");
                            antri.add("Alex");
                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Yuni");
                            antri.add("Vini");
                            antri.add("Tono");
                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Alex");
                            antri.add("Rian");
                            antri.add("Raffi");
                            antri.add("Andre");
                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            String ant = antri.size() + "/5";
                            tfKuota.setText(ant);
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            } else if (d.getNama().equalsIgnoreCase("Dr Bryan")) {
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Bryan'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Rudi");
                            antri.add("Roy");
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Vania");
                            antri.add("Rani");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            String ant = antri.size() + "/12";
                            tfKuota.setText(ant);

                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Vania");
                            antri.add("Rani");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            String ant = antri.size() + "/12";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Roy");
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Vania");
                            antri.add("Rani");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            String ant = antri.size() + "/12";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Vania");
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            antri.add("Roy");
                            String ant = antri.size() + "/12";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Vania");
                            antri.add("Rani");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            String ant = antri.size() + "/12";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            String ant = antri.size() + "/0";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            String ant = antri.size() + "/0";
                            tfKuota.setText(ant);
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            } else {
                //    (d.getNama().equalsIgnoreCase("Dr Axel"))
                try {
                    String query = "SELECT NAMA FROM DOKTER WHERE NAMA LIKE 'Dr Axel'";
                    conn = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xepdb1", "hr", "hr");
                    stmt = conn.createStatement();
                    ResultSet rset = stmt.executeQuery(query);
                    while (rset.next()) {
                        if (box.equalsIgnoreCase("Senin")) {
                            txJadwal.setText("Senin Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Vania");
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Nina");
                            antri.add("Jonathan");

                            String ant = antri.size() + "/15";
                            tfKuota.setText(ant);

                        } else if (box.equalsIgnoreCase("Selasa")) {
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Vania");
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            antri.add("Roy");
                            String ant = antri.size() + "/15";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Rabu")) {
                            txJadwal.setText("Rabu Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Jonathan");
                            antri.add("Nata");
                            antri.add("Nina");
                            antri.add("Rey");
                            antri.add("Roy");
                            antri.add("Nina");
                            antri.add("Tono");
                            String ant = antri.size() + "/15";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Kamis")) {
                            txJadwal.setText("Kamis Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Nata");
                            antri.add("Rey");
                            antri.add("Vania");
                            antri.add("Rani");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            String ant = antri.size() + "/15";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Jumat")) {
                            txJadwal.setText("Jumat Pukul 10.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            txJadwal.setText("Selasa Pukul 8.00-17.00 WIB");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            antri.add("Vania");
                            antri.add("Rani");
                            antri.add("Nina");
                            antri.add("Jonathan");
                            String ant = antri.size() + "/15";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Sabtu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            String ant = antri.size() + "/0";
                            tfKuota.setText(ant);
                        } else if (box.equalsIgnoreCase("Minggu")) {
                            txJadwal.setText("Libur");
                            txNamaDokter.setText(rset.getString(1));
                            antri.clear();
                            String ant = antri.size() + "/0";
                            tfKuota.setText(ant);
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            btnAntri.setEnabled(true);
        }

    }//GEN-LAST:event_btnJadwalActionPerformed

    private void txNamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaDokterActionPerformed

    private void boxJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxJadwalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJadwalActionPerformed

    private void btnSelanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelanjutnyaActionPerformed
        tfQueue.setText("");
        antri.forEach((Object element) -> {
            tfQueue.append("" + element + "\n");
        });
        if (antri.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Antrian kosong");
        } else {
            antri.poll();
            counter++;
            tfAntrian.setText(String.valueOf(counter));

        }

    }//GEN-LAST:event_btnSelanjutnyaActionPerformed

    private void tfAntrianSayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAntrianSayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAntrianSayaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxJadwal;
    private javax.swing.JButton btnAntri;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSelanjutnya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAntrian;
    private javax.swing.JTextField tfAntrianSaya;
    private javax.swing.JTextField tfKonfirmasi;
    private javax.swing.JTextField tfKuota;
    private javax.swing.JTextArea tfQueue;
    private javax.swing.JTextField txJadwal;
    private javax.swing.JTextField txNamaDokter;
    // End of variables declaration//GEN-END:variables
}
