
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ROG
 */
public class ListDokter extends javax.swing.JFrame {

    /**
     * Creates new form ListDokter
     */  
    isiHospital base=new isiHospital();
    public ListDokter(java.awt.Frame parent, boolean modal) {
        initComponents();
     //   this.base=data;
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        THT = new javax.swing.JMenu();
        txDenata = new javax.swing.JMenuItem();
        txArsel = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        txFrans = new javax.swing.JMenuItem();
        txBryan = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        txAxel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Beranda");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel2.setText("Selamat datang, silahkan memilih dokter untuk reservasi");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_langkah1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel4.setText("1. Silahkan pilih menu \"Input\" di pojok kiri atas");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel5.setText("INSTRUKSI");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel6.setText("2. Silahkan memilih poli Spesialis atau Umum");

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel7.setText("3. Pilih dokter yang tersedia");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_langkah3.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_langkah2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(141, 141, 141))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon input.png"))); // NOI18N
        jMenu1.setText("INPUT");
        jMenu1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setForeground(new java.awt.Color(0, 0, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon poli.png"))); // NOI18N
        jMenu5.setText("POLI");
        jMenu5.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setForeground(new java.awt.Color(0, 0, 0));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon poli spesialis.png"))); // NOI18N
        jMenu6.setText("Spesialis");
        jMenu6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        THT.setBackground(new java.awt.Color(255, 255, 255));
        THT.setForeground(new java.awt.Color(0, 0, 0));
        THT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon THT.png"))); // NOI18N
        THT.setText("THT");
        THT.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        txDenata.setBackground(new java.awt.Color(255, 255, 255));
        txDenata.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        txDenata.setForeground(new java.awt.Color(0, 0, 0));
        txDenata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon doctor.png"))); // NOI18N
        txDenata.setText("Dr Denata");
        txDenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDenataActionPerformed(evt);
            }
        });
        THT.add(txDenata);

        txArsel.setBackground(new java.awt.Color(255, 255, 255));
        txArsel.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        txArsel.setForeground(new java.awt.Color(0, 0, 0));
        txArsel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon doctor.png"))); // NOI18N
        txArsel.setText("Dr Arsel");
        txArsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txArselActionPerformed(evt);
            }
        });
        THT.add(txArsel);

        jMenu6.add(THT);

        jMenu8.setBackground(new java.awt.Color(255, 255, 255));
        jMenu8.setForeground(new java.awt.Color(0, 0, 0));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon Jantung.png"))); // NOI18N
        jMenu8.setText("JANTUNG");
        jMenu8.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        txFrans.setBackground(new java.awt.Color(255, 255, 255));
        txFrans.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        txFrans.setForeground(new java.awt.Color(0, 0, 0));
        txFrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon doctor.png"))); // NOI18N
        txFrans.setText("Dr Frans");
        txFrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFransActionPerformed(evt);
            }
        });
        jMenu8.add(txFrans);

        txBryan.setBackground(new java.awt.Color(255, 255, 255));
        txBryan.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        txBryan.setForeground(new java.awt.Color(0, 0, 0));
        txBryan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon doctor.png"))); // NOI18N
        txBryan.setText("Dr Bryan");
        txBryan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBryanActionPerformed(evt);
            }
        });
        jMenu8.add(txBryan);

        jMenu6.add(jMenu8);

        jMenu5.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setForeground(new java.awt.Color(0, 0, 0));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon poli umum.png"))); // NOI18N
        jMenu7.setText("UMUM");
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        txAxel.setBackground(new java.awt.Color(255, 255, 255));
        txAxel.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        txAxel.setForeground(new java.awt.Color(0, 0, 0));
        txAxel.setText("Dr Axel");
        txAxel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAxelActionPerformed(evt);
            }
        });
        jMenu7.add(txAxel);

        jMenu5.add(jMenu7);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon logout 2.png"))); // NOI18N
        jMenu2.setText("KELUAR");
        jMenu2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txDenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDenataActionPerformed
        // TODO add your handling code here:
    //    base.isiDataHospital(new Dokter("Dr Denata","123","THT"))
     ///    isiHospital base=new isiHospital();
     
        String wav="C:\\Users\\ROG\\Documents\\NetBeansProjects\\SDL_Project\\src\\Audio\\wav\\Jadwal denata.wav";
         Jadwal jd=new Jadwal (this,true,base);
        jd.setVisible(true);
        try {
        Dokter dk=new Dokter("215314107","Dr Denata","THT");
        base.isiDataHospital(dk);
        JOptionPane.showMessageDialog(null, dk.getNama());
        MusicStuff(wav);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txDenataActionPerformed

    private void txArselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txArselActionPerformed
        // TODO add your handling code here:
        String wav="C:\\Users\\ROG\\Documents\\NetBeansProjects\\SDL_Project\\src\\Audio\\wav\\Jadwal Arsel.wav";
         Jadwal jd=new Jadwal (this,true,base);
        jd.setVisible(true);
          try {
        Dokter dk=new Dokter("215314098","Dr Arsel","THT");
        base.isiDataHospital(dk);
        JOptionPane.showMessageDialog(null, dk.getNama());
         MusicStuff(wav);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
    }//GEN-LAST:event_txArselActionPerformed

    private void txFransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFransActionPerformed
        // TODO add your handling code here:
        String wav="C:\\Users\\ROG\\Documents\\NetBeansProjects\\SDL_Project\\src\\Audio\\wav\\Jadwal Frans.wav";
         Jadwal jd=new Jadwal (this,true,base);
        jd.setVisible(true);
          try {
        Dokter dk=new Dokter("215314092","Dr Frans","Jantung");
        base.isiDataHospital(dk);
        JOptionPane.showMessageDialog(null, dk.getNama());
         MusicStuff(wav);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txFransActionPerformed

    private void txBryanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBryanActionPerformed
        // TODO add your handling code here:
        String wav="C:\\Users\\ROG\\Documents\\NetBeansProjects\\SDL_Project\\src\\Audio\\wav\\Jadwal Bryan.wav";
        Jadwal jd=new Jadwal (this,true,base);
        jd.setVisible(true);
          try {
        Dokter dk=new Dokter("215314102","Dr Bryan","Jantung");
        base.isiDataHospital(dk);
        JOptionPane.showMessageDialog(null, dk.getNama());
         MusicStuff(wav);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txBryanActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void txAxelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAxelActionPerformed
        String wav="C:\\Users\\ROG\\Documents\\NetBeansProjects\\SDL_Project\\src\\Audio\\wav\\Jadwal Axel.wav";
         Jadwal jd=new Jadwal (this,true,base);
        jd.setVisible(true);
        try {
        Dokter dk=new Dokter("215314108","Dr Axel","Umum");
        base.isiDataHospital(dk);
        JOptionPane.showMessageDialog(null, dk.getNama());
        MusicStuff(wav);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txAxelActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?");
       switch(opsi){
            case JOptionPane.YES_OPTION:
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    
     public void MusicStuff(String music) {
        try {
            File musicPath = new File(music);

            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);
                
                JOptionPane.showMessageDialog(null, "Oke Untuk Stop");
              //  long clipTimePosition = clip.getMicrosecondPosition();
                clip.stop();

//                JOptionPane.showMessageDialog(null, "Klik Oke Sekali Lagi");
//                clip.setMicrosecondPosition(clipTimePosition);
//                clip.start();
            } else {
                JOptionPane.showMessageDialog(null, " Tidak Menemukan File ");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu THT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem txArsel;
    private javax.swing.JMenuItem txAxel;
    private javax.swing.JMenuItem txBryan;
    private javax.swing.JMenuItem txDenata;
    private javax.swing.JMenuItem txFrans;
    // End of variables declaration//GEN-END:variables
}
